@extends('master')
@section('content')

 <div class="container">
 <div class="row justify-content-left ">
<p></p>


	 <div class="k_cheading">
		<h1>ISUW 2022 <span class="k_greencolor">Participating Utilities </span> </h1>
		<img src="/public/uploads/images/kborder_bottom.png" alt=""> 
	</div>
<p></p>
<div class="col-lg-3"><div class="logo-div"><a href="http://www.mvvnl.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/partner/Madhyanchal Vidyut Vitaran Nigam Limited.png" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://www.apeasternpower.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/partner/Andhra Pradesh Eastern Power Distribution Company.jpg" alt=""  height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.upcl.org/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/partner/Uttarakhand Power Corporation Limited.jpg" alt=""  height="125" /> </a></div></div>

<div class="col-lg-3"><div class="logo-div"><a href="https://www.bsesdelhi.com/web/bypl#loaded" target="_blank" rel="noopener noreferrer"><img style="margin: 0 auto; height: 44px; margin-top: 27px;" src="https://www.isgw.in/public/uploads/utility/1641110101.png" alt=""></a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.bsesdelhi.com/web/brpl" target="_blank" rel="noopener noreferrer"><img style="margin: 0 auto; height: 50px; width: 151px; margin-top: 23px;" src="https://www.isgw.in/public/uploads/utility/1641110129.png" alt=""></a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.cesc.co.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/1641223726.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://bescom.co.in/SCP/Myhome.aspx" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/1641223586.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.cspdcl.co.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/Chhattisgarh State Power Distribution Co. Ltd.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://dhbvn.org.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/DHBVN_Logo.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://kseb.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/Kerala State Electricity Board Ltd.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="http://www.tatapower-ddl.com/" target="_blank" rel="noopener noreferrer"><img src="https://www.isgw.in/public/uploads/utility/1641110211.png" alt="" width="213" height="102"></a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.tatapower.com/" target="_blank" rel="noopener noreferrer"><img src="https://www.isgw.in/public/uploads/utility/1641110147.png" style="margin-top:-10px;"></a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://posoco.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="http://www.isgw.in/beta/wp-content/uploads/2020/02/POSOCO_Final_Logo.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.noidapower.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/1641486892.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.torrentpower.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/Torrent Power Ltd.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.tpcentralodisha.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/TPCODL.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="http://www.mpwz.co.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/Madhya Pradesh Pachim Kshetra Vidyut Vitran Co Ltd.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.mahadiscom.in/en/home/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/MSEDCL.png" alt="" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://pspcl.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/PSPCL-English-Logo.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.tsecl.in/irj/go/km/docs/internet/TRIPURA/webpage/pages/Home.html" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/wp-content/uploads/2021/02/Tripura.jpg" alt="" height="125" /> </a></div></div>

<div class="col-lg-3"><div class="logo-div"><a href="https://www.tpadl.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/1646052123.png" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://www.apdcl.org/website/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/1646052173.png" alt=""  height="125" /> </a></div></div>
 <div class="k_cheading">
		<h1>INDIAN <span class="k_greencolor">Participating Utilities </span> </h1>
		<img src="/public/uploads/images/kborder_bottom.png" alt=""> 
	</div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.upenergy.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/Uttar Pradesh Power Corporation Limited.jpg" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://jbvnl.co.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/Jharkhand Bijli Vitran Nigam limited.jpg" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://energy.rajasthan.gov.in/content/raj/energy-department/en/home.html" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/Jodhpur  Vidyut Vitran Nigam Limited.jpg" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://nbpdcl.co.in/(S(rp10ls3ynj31m5dqaxft2vwz))/frmhome.aspx" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/North Bihar Power Distribution limited.jpg" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://www.fedco.co.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/Feedback Energy Distribution company limited.png" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://www.sbpdcl.co.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/SBLogo.jpg" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://www.dded.gov.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/Duman & Diu.png" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://www.ndmc.gov.in/faq/veterinary_faqs.aspx" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/NDMC 2.png" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://www.guvnl.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/Logo_GUVNL.png" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://www.dgvcl.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/DGVCL.jpg" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://www.mgvcl.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/MGVCL.jpg" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://www.pgvcl.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/PVVNL-Logo.png" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="http://www.ugvcl.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/ugvcl.jpg" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://www.uhbvn.org.in/web/portal/home" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/UHBVN.png" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://www.hpseb.in/irj/go/km/docs/internet/New_Website/Pages/Home.html" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/hpsebl (1).gif" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="http://www.jkspdc.nic.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/J&K.png" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://jamshedpur.nic.in/jusco/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/Jamshedpur utility.png" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://mescom.karnataka.gov.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/MESCOM.png" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://hescom.karnataka.gov.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/HESCOM.jpg" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://gescom.karnataka.gov.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/GESCOM.jpg" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://cescmysore.karnataka.gov.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/CESC Mysore.jpg" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://portal.mpcz.in/web/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/mpmkvvcl (1).png" alt="" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://www.bestundertaking.com/in/iis6954.asp?lang=en#popup1" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/Brihanmmumbai (1).png" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://www.adanielectricity.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/adani.jpg" alt=""  /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://electricity.py.gov.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/Puducherry.jpg" alt=""  /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://power.sikkim.gov.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/Sikkim.png" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://www.tangedco.gov.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/TANGDCL.png" alt=""   /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://tsnpdcl.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/npdcl_Telangana.png" alt=""   /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://www.dvc.gov.in/dvcwebsite_new1/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/Damodar_Valley_Corporation (1).png" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://www.wbsedcl.in/irj/go/km/docs/internet/new_website/Home.html" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/WBSEDCL.png" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://www.upcl.org/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/UPCL.png" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://kesco.co.in/wss/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/KESCO.png" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://pvvnl.org/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/PVVNL-Logo (1).png" alt=""  height="125" /> </a></div></div> 


 <div class="k_cheading">
		<h1>INTERNATIONAL <span class="k_greencolor">Participating Utilities </span> </h1>
		<img src="/public/uploads/images/kborder_bottom.png" alt=""> 
	</div>
<div class="col-lg-3"><div class="logo-div"><a href="http://www.bpdb.gov.bd/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/Bangladesh Power Development Board.jpg" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://ceb.lk/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/Ceylon Electricity Board.png" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://www.iec.co.il/en/pages/default.aspx" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/Israel Electric Corporation.png" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://www.edfenergy.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/Électricité de France.png" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://www.nea.org.np/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/Nepal Electricity Authority.png" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://en.evn.com.vn/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/Vietnam Electricity.png" alt=""  height="125" /> </a></div></div> 
<div class="col-lg-3"><div class="logo-div"><a href="https://www.bpc.bt/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://isgw.in/public/uploads/utility/Bhutan Power Corporation Limited.png" alt=""  height="125" /> </a></div></div> 

<!--<div class="col-lg-3"><div class="logo-div"><a href="https://www.tssouthernpower.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="http://www.isgw.in/beta/wp-content/uploads/2020/02/Southern-Power-Distribution-Company-of-Telangana-State-Ltd.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.indiapower.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="http://www.isgw.in/beta/wp-content/uploads/2020/02/INDIA-POWER.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://energy.rajasthan.gov.in/avvnl" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  style="" src="http://www.isgw.in/beta/wp-content/uploads/2020/02/Ajmer-Vidyut-Vitran-Nigam-Ltd.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="http://www.ugvcl.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="http://www.isgw.in/beta/wp-content/uploads/2020/02/Uttar-Gujarat-Vij-Company-Ltd..jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://cescmysore.karnataka.gov.in/english" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/Chamudeshwari Electricity Supply Company Ltd.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.dgvcl.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/Dakshin Gujarat Vij Co Ltd.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.guvnl.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/Gujarat Urja Vikas Nigam Ltd..jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.hpseb.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/Himachal Pradesh State Electricity Board.gif" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://hescom.karnataka.gov.in/english" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/Hubli Electricity Supply Co. Ltd.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="http://www.jkspdc.nic.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/J&K.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://energy.rajasthan.gov.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/Jaipur Vidyut Vitran Nigam Ltd.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/JdVVNLa.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://jbvnl.co.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/Jharkhand Bijli Vitran Nigam Limited.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.mgvcl.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/Madhya Gujarat Vij. Co. Ltd.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="http://www.mvvnl.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/Madhyanchal Vidyut Vitran Nigam Ltd.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://mspcl.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/Manipur State Power Distribution Company Ltd..jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://meecl.nic.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/Meghalaya Power Distribution Corporation Ltd.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.mescom.org.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/MESCOM.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://nbpdcl.co.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/North Bihar Power Distribution Company Limited.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.ntpc.co.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/NTPC.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.pgvcl.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/Paschim Gujarat Vij Company Limited.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://pvvnl.org/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/Paschimanchal Vidyut Vitran Nigam Ltd.png" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="http://puvvnl.up.nic.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/Purvanchal Vidyut Vitran Nigam Ltd.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.apspdcl.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/South Bihar Power Distribution Company Limited.jpg" alt="" height="125" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.tangedco.gov.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/Tamil Nadu Electricity Board.jpg" alt="" height="125" /> </a></div></div>


<div class="col-lg-3"><div class="logo-div"><a href="https://www.uhbvn.org.in/web/portal/home" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/UHBVN.png" alt="" height="125" /> </a></div></div>

<div class="col-lg-3"><div class="logo-div"><a href="https://www.wbsedcl.in/irj/go/km/docs/internet/new_website/Home.html" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/West Bengal State Electricity Dist. Co. Ltd.png" alt=""  /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://tsnpdcl.in/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="https://www.isgw.in/public/uploads/utility/The Northern Power Distribution Company of Telangana Limited(TSNPDCL).png" alt="" height="43" /> </a></div></div>
<div class="col-lg-3"><div class="logo-div"><a href="https://www.adanielectricity.com/" target="_blank" rel="noopener noreferrer"><img class="alignleft size-medium wp-image-38051"  src="http://www.isgw.in/public/uploads/partner/Adani Electricity Mumbai Ltd.png" alt="" /> </a></div></div>
-->
<p></p>
<p style="text-align:center; font-size:16px;"><a href="https://www.isgw.in/participating-utilies-2021" class="getstartedd ">Participating Utilities 2021</a></p>

<p></p>
</div>
</div>

@endsection